.travis.yml

Adding travis-ci to viz. Build passed in my fork
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/viz/1)

Adding Travis-ci

---

src/js/controllers/ieee8500/Ieee8500Controller.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/viz/3)

fixing the simulation subscription topic

---

runConfig.ts
server.js
src/js/views/ieee8500/Ieee8500View.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/viz/5)

Fix labels on Firefox

---

Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/viz/9)

updated workdir, updated copy

---

Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/viz/11)

Updated dockerfile to specify webpack version

---

Dockerfile
build-docker.sh
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/viz/18)

Added versioning for docker, updated package.json

---

Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/viz/24)

updated dockerfile to support new package.json

---

Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/viz/25)

updated to remove webpack, now npm run webpack

---

src/js/models/AppState.ts
src/js/models/default-simulation-config.ts
src/js/models/fncs-output/FncsOutput.ts
src/js/models/message-requests/GetModelDictionaryRequest.ts
src/js/models/message-requests/SimulationOutputPayload.ts
src/js/models/simulation-config-options.ts
src/js/models/simulation-output/SimulationOutput.ts
src/js/models/simulation-output/SimulationOutputMeasurement.ts
src/js/rootReducer.ts
src/js/services/MessageService.ts
src/js/services/SimulationControlService.ts
src/js/services/StompClient.ts
src/js/services/stomp-client.ts
src/js/views/database-browser/blazegraph/BlazeGraph.tsx
src/js/views/database-browser/blazegraph/BlazeGraphContainer.tsx
src/js/views/main/Main.tsx
src/js/views/main/MainContainer.tsx
src/js/views/main/main-actions.ts
src/js/views/main/main-reducers.ts
src/js/views/plot/Plot.styles.scss
src/js/views/plot/PlotContainer.tsx
src/js/views/simulation-status-logger/SimulationStatusLoggerContainer.tsx
src/js/views/stomp-client/StompClient.styles.scss
src/js/views/stomp-client/StompClient.tsx
src/js/views/stomp-client/StompClientContainer.tsx
src/js/views/topology/LabelContainer.tsx
src/js/views/topology/SimulationConfigForm.tsx
src/js/views/topology/TopologyModelRenderer.styles.scss
src/js/views/topology/TopologyModelRenderer.tsx
src/js/views/topology/TopologyModelRendererContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/viz/26)

Dynamic request

---

.travis/build-docker.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/viz/29)

Updated docker build version to include githash

---

src/app/models/message-requests/SimulationOutputPayload.ts
src/app/models/simulation-output/SimulationOutput.ts
src/app/services/SimulationControlService.ts
src/app/views/app-bar/AppBar.tsx
src/app/views/main/MainContainer.tsx
src/app/views/topology/TopologyModelRenderer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/viz/38)

- Change code to adapt to the new simulation output

---

.travis.yml
.travis/build-docker.sh

Updated travis build 
- error on docker push failure to allow travis notifications
- allow builds that run across the hour boundary
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/viz/41)

Updated travis build 

---

src/app/simulation/measurement-graph/MeasurementGraph.scss
src/app/simulation/measurement-graph/MeasurementGraph.tsx
src/app/simulation/measurement-graph/MeasurementGraphContainer.tsx

- Change the harded node names to display for the power plots
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/43)

- Fix measurement displaying bug in the plots

---

src/app/models/message-requests/GetTopologyModelRequest.ts
src/app/shared/views/dropdown-menu/DropdownMenu.tsx
src/app/simulation/simulation-status-logger/SimulationStatusLogger.scss

- Fix dropdown menu not closing when an alreadly selected item is reselected
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/44)

- Change the subscribe url for receiving topology model

---

package.json
src/app/models/message-requests/GetModelDictionaryRequest.ts
src/app/services/SimulationOutputService.ts
src/app/services/StompClientService.ts
src/app/simulation/label/LabelContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/45)

For release

---

src/app/topology-renderer/TopologyRendererContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/47)

 added update command in payload for toggle switch

---

src/app/simulation/simulation-status-logger/views/simulation-status-log-message/SimulationStatusLogMessage.tsx
src/app/stomp-client/StompClientContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/53)

Fix stomp client

---

src/app/stomp-client/StompClientContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/57)

checking for empty string before parsing the JSON

---

runConfig.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/66)

Updated version

---

src/app/App.tsx
src/app/navigation/Navigation.scss
src/app/shared/buttons/icon-button/IconButton.scss
src/app/shared/buttons/icon-button/IconButton.tsx
src/app/shared/ripple/Ripple.tsx
src/app/shared/simulation/SimulationControlService.ts
src/app/shared/simulation/topics.ts
src/app/simulation/label/LabelContainer.tsx
src/app/simulation/measurement-graph/MeasurementGraphContainer.tsx
src/app/simulation/simulation-control/SimulationControl.scss
src/app/simulation/simulation-control/SimulationControl.tsx
src/app/simulation/simulation-control/SimulationControlContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/81)

Stop pause resume simulation

---

src/app/shared/simulation/SimulationControlService.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/82)

Update the internal status variable when simulation status changes

---

.gitignore
src/app/App.tsx
src/app/navigation/Navigation.tsx
src/app/navigation/drawer/DrawerItemGroup.scss
src/app/navigation/drawer/DrawerItemGroup.tsx
src/app/shared/buttons/basic-button/BasicButton.scss
src/app/shared/simulation/SimulationQueue.ts
src/app/simulation/simulation-control/SimulationControl.scss
src/app/simulation/simulation-control/SimulationControl.tsx
src/app/simulation/simulation-control/SimulationControlContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/84)

Show simulation ID when simulation ID is sent back

---

src/app/shared/form/form-control/FormControl.scss
src/app/shared/topology/Capacitor.ts
src/app/topology-renderer/TopologyRenderer.tsx
src/app/topology-renderer/TopologyRendererContainer.tsx
src/app/topology-renderer/menus/capacitor-menu/CapacitorMenu.scss
src/app/topology-renderer/menus/capacitor-menu/CapacitorMenu.tsx
src/app/topology-renderer/models/CapacitorControlMode.ts
src/app/topology-renderer/models/CapacitorVarUpdateRequest.ts
src/app/topology-renderer/models/CapacitorVoltUpdateRequest.ts
src/app/topology-renderer/models/CapacityMenuFormValue.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/85)

Update capacitor menu

---

.travis/build-docker.sh
Dockerfile

Added version information to dockerfile and travis configuration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/92)

Updated docker and travis for version

---

src/app/simulation/simulation-control/SimulationControl.scss
src/app/simulation/simulation-control/SimulationControl.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/102)

Now clicking on simulation ID will copy it to clipboard

---

src/app/navigation/drawer/Drawer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/113)

Only rerender drawer component when needed

---

src/app/models/default-application-state.ts
src/app/simulation/event-summary/EventSummary.tsx
src/app/simulation/simulation-control/SimulationControlContainer.tsx
src/app/simulation/simulation-status-logger/SimulationStatusLoggerContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/116)

Simulation logs are now showing, they were not because the subscription to get the logs was closed unexpectedly

---

src/app/simulation/label/LabelContainer.tsx
src/app/simulation/measurement-chart/MeasurementChartContainer.tsx
src/app/simulation/simulation-configuration/SimulationConfigurationEditor.tsx
src/app/simulation/simulation-configuration/views/SimulationConfigurationFormGroup/SimulationConfigurationFormGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/117)

Update simulation name input field when a different model is selected

---

src/app/App.tsx
src/app/available-applications-and-services/AvailableApplicationsAndServices.tsx
src/app/models/default-application-state.ts
src/app/models/message-requests/GetAvailableApplicationsAndServicesRequest.ts
src/app/shared/Service.ts
src/app/shared/state-store/ApplicationState.ts
src/app/simulation/applications/AvailableApplicationList.scss
src/app/simulation/applications/AvailableApplicationList.tsx
src/app/simulation/applications/AvailableApplicationListItem.scss
src/app/simulation/applications/AvailableApplicationListItem.tsx
src/app/simulation/applications/models/DisableApplicationRequest.ts
src/app/simulation/applications/models/EnableApplicationRequest.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/122)

Add a tab to list all applications

---

src/app/shared/form/textarea/TextArea.tsx
src/app/simulation/simulation-status-logger/SimulationStatusLoggerContainer.tsx
src/app/stomp-client/StompClient.scss
src/app/stomp-client/StompClient.tsx

…ectable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/123)

2 bug fixes

---

src/app/simulation/measurement-chart/MeasurementChart.scss
src/app/simulation/measurement-chart/MeasurementChartContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/126)

added power and tap plots for 9500 model

---

src/app/App.tsx
src/app/available-applications-and-services/AvailableApplicationsAndServices.tsx
src/app/models/default-application-state.ts
src/app/models/message-requests/GetAvailableApplicationsAndServicesRequest.ts
src/app/shared/Service.ts
src/app/shared/form/form-control/FormControl.tsx
src/app/shared/form/input/Input.scss
src/app/shared/form/input/Input.tsx
src/app/shared/form/textarea/TextArea.tsx
src/app/shared/state-store/ApplicationState.ts
src/app/shared/test-manager/FaultEvent.ts
src/app/shared/test-manager/FaultEventTable.tsx
src/app/simulation/applications/AvailableApplicationList.scss
src/app/simulation/applications/AvailableApplicationList.tsx
src/app/simulation/applications/AvailableApplicationListItem.scss
src/app/simulation/applications/AvailableApplicationListItem.tsx
src/app/simulation/applications/models/DisableApplicationRequest.ts
src/app/simulation/applications/models/EnableApplicationRequest.ts
src/app/simulation/measurement-chart/MeasurementChart.scss
src/app/simulation/measurement-chart/MeasurementChartContainer.tsx
src/app/simulation/simulation-configuration/SimulationConfigurationEditor.tsx
src/app/simulation/simulation-configuration/views/TestConfigurationFormGroup/FaultEventForm.tsx
src/app/simulation/simulation-configuration/views/TestConfigurationFormGroup/TestConfigurationFormGroup.tsx
src/app/simulation/simulation-status-logger/SimulationStatusLoggerContainer.tsx
src/app/stomp-client/StompClient.scss
src/app/stomp-client/StompClient.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/127)

Update beta release

---

src/app/simulation/simulation-configuration/SimulationConfigurationEditor.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/132)

Send MRID's in an array for test config object

---

src/app/simulation/simulation-configuration/views/TestConfigurationFormGroup/FaultEventForm.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/134)

Use ConductingEquipmentMRID if it exists or just MRID otherwise

---

src/app/simulation/simulation-status-logger/SimulationStatusLogger.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/141)

Prepend an index to each message component to make its key unique

---

src/app/simulation/simulation-labels/SimulationLabel.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/144)

Update the class name to locate the nodes to attach the labels to

---

src/app/data-browser/logs/LogsContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/146)

add process type

---

src/app/App.tsx
src/app/models/default-application-state.ts
src/app/shared/simulation/SimulationControlService.ts
src/app/shared/state-store/ApplicationState.ts
src/app/simulation/applications/AvailableApplicationList.tsx
src/app/simulation/event-summary/EventSummary.tsx
src/app/simulation/simulation-control/SimulationControlContainer.tsx
src/app/simulation/simulation-status-logger/SimulationStatusLoggerContainer.tsx
src/app/simulation/voltage-violation/VoltageViolation.scss
src/app/simulation/voltage-violation/VoltageViolation.tsx
src/app/simulation/voltage-violation/VoltageViolationContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/145)

Voltage violation

---

src/app/shared/simulation/SimulationControlService.ts
src/app/simulation/voltage-violation/VoltageViolation.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/148)

Show start button when simulation completes

---

src/app/data-browser/logs/QueryLogsForm.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/149)

Bug fix/browse data logs simulation id dropdown not showing selected

---

src/app/topology-renderer/TopologyRenderer.tsx
src/app/topology-renderer/TopologyRendererContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/153)

fix the small model scaling and include points on 0.0 x or y values

---

src/app/simulation/simulation-configuration/SimulationConfigurationEditor.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/158)

fix duplicate mrid for ACLineSegment

---

src/app/shared/buttons/basic-button/BasicButton.tsx
src/app/shared/buttons/icon-button/IconButton.tsx
src/app/shared/dialog/Dialog.tsx
src/app/shared/form/select/OptionList.scss
src/app/shared/form/select/OptionListFilter.scss
src/app/shared/form/select/Select.scss
src/app/shared/form/select/Select.tsx
src/app/shared/form/select/SelectedOptionList.scss
src/app/shared/form/select/SelectedOptionList.tsx
src/app/shared/overlay/OverlayService.tsx
src/app/shared/pop-up/PopUp.scss
src/app/shared/pop-up/PopUp.tsx
src/app/shared/ripple/Ripple.scss
src/app/shared/ripple/Ripple.tsx
src/app/simulation/simulation-control/SimulationControl.tsx
src/app/simulation/simulation-control/views/plot-model-creator/PlotModelCreator.tsx
src/app/topology-renderer/TopologyRenderer.tsx
src/app/topology-renderer/TopologyRendererContainer.tsx
src/app/topology-renderer/views/capacitor-menu/CapacitorMenu.tsx
src/app/topology-renderer/views/regulator-menu/RegulatorMenu.tsx
src/app/topology-renderer/views/switch-menu/SwitchMenu.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/161)

Component improvements

---

src/app/shared/simulation/SimulationOutputPayload.ts
src/app/shared/simulation/SimulationOutputService.ts
src/app/simulation/measurement-chart/MeasurementChartContainer.tsx
src/app/simulation/simulation-labels/SimulationLabelsContainer.tsx

Not sure if this change will work, I didn't test it with the new format
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/160)

Update to new simulation output format

---

src/app/data-browser/DataBrowser.scss
src/app/data-browser/logs/Logs.scss
src/app/data-browser/logs/LogsContainer.tsx
src/app/data-browser/logs/QueryLogsForm.scss
src/app/data-browser/logs/QueryLogsForm.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/170)

Make the response section in Logs data browser more responsive

---

src/app/data-browser/powergrid-models/PowergridModels.tsx
src/app/shared/buttons/basic-button/BasicButton.tsx
src/app/shared/buttons/icon-button/IconButton.scss
src/app/shared/buttons/icon-button/IconButton.tsx
src/app/shared/form/form-control/FormControl.scss
src/app/shared/misc.ts
src/app/shared/ripple/Ripple.tsx
src/app/shared/wait/Wait.tsx
src/app/simulation/simulation-configuration/views/test-configuration/TestConfiguration.tsx
src/app/stomp-client/StompClient.scss
src/app/stomp-client/StompClient.tsx
src/app/stomp-client/StompClientContainer.tsx
src/styles.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/169)

Add options to export stomp client response as CSV and JSON

---

src/app/shared/form/textarea/TextArea.scss
src/app/shared/form/textarea/TextArea.tsx
src/app/stomp-client/StompClient.scss
src/styles.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/173)

Make textarea's input box resizable

---

src/app/shared/tabs/TabGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/174)

When switching to a new tab, we want to reset the scroll to 0

---

src/app/shared/form/textarea/TextArea.tsx
src/app/simulation/simulation-configuration/views/service-configuration/ServiceConfigurationEntry.tsx
src/styles.scss

- Change tooltip text in service configuration tab
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/175)

- Recalculate text box's bounding box when the resize begins

---

src/app/shared/form/select/Select.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/177)

Implement fuzzy searching in select component

---

src/app/shared/notification-banner/NotificationBanner.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/179)

Check for existence of notification banner's container before removing

---

src/app/shared/buttons/icon-button/IconButton.tsx
src/app/topology-renderer/TopologyRenderer.scss
src/app/topology-renderer/TopologyRenderer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/182)

Add a button to reset the topology renderer's zoom and translation

---

src/app/shared/topology/Node.ts
src/app/shared/topology/Switch.ts
src/app/topology-renderer/TopologyRenderer.tsx
src/app/topology-renderer/TopologyRendererContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/185)

Render switches by default initially

---

src/app/App.tsx
src/app/topology-renderer/TopologyRendererContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/191)

We don't want to cache feeder models in session storage anymore

---

src/styles.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/193)

Show a resize cursor while resizing textarea box

---

src/app/models/default-application-state.ts
src/app/shared/state-store/ApplicationState.ts
src/app/shared/tabs/ActiveTabIndicator.scss
src/app/shared/tabs/TabGroup.scss
src/app/shared/tabs/TabGroup.tsx
src/app/shared/test-manager/CommOutageEvent.ts
src/app/shared/test-manager/CommandEvent.ts
src/app/shared/test-manager/CommandEventTable.scss
src/app/shared/test-manager/CommandEventTable.tsx
src/app/shared/test-manager/FaultEvent.ts
src/app/shared/test-manager/index.ts
src/app/simulation/event-summary/CommandEventSummary.tsx
src/app/simulation/event-summary/EventSummary.tsx
src/app/simulation/simulation-configuration/SimulationConfigurationEditor.tsx
src/app/simulation/simulation-configuration/views/service-configuration/ServiceConfiguration.scss
src/app/simulation/simulation-configuration/views/test-configuration/CommOutageEventForm.tsx
src/app/simulation/simulation-configuration/views/test-configuration/CommOutageEventSummaryTable.scss
src/app/simulation/simulation-configuration/views/test-configuration/CommandEventSummaryTable.scss
src/app/simulation/simulation-configuration/views/test-configuration/CommandEventSummaryTable.tsx
src/app/simulation/simulation-configuration/views/test-configuration/FaultEventSummaryTable.scss
src/app/simulation/simulation-configuration/views/test-configuration/TestConfiguration.scss
src/app/simulation/simulation-configuration/views/test-configuration/TestConfiguration.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/192)

Read command events from events.json file and display them

---

src/app/simulation/voltage-violation/VoltageViolation.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/197)

Reposition voltage violation counts component

---

src/app/simulation/simulation-configuration/views/test-configuration/TestConfiguration.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/194)

Merge uploaded events with events created by the users so far

---

src/app/simulation/alarms/views/new-alarm-notification/NewAlarmNotification.scss
src/app/simulation/alarms/views/new-alarm-notification/NewAlarmNotification.tsx
src/app/simulation/simulation-labels/SimulationLabel.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/200)

Show the new alarm notification on the 'Alarms' tab

---

src/app/shared/simulation/SimulationOutputMeasurement.ts
src/app/shared/simulation/SimulationOutputService.ts
src/app/shared/topology/Switch.ts
src/app/simulation/topology-renderer/TopologyRenderer.tsx
src/app/simulation/topology-renderer/TopologyRendererContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/201)

Update switches based on simulation output

---

src/app/simulation/topology-renderer/views/node-searcher/NodeSearcher.common.scss
src/app/simulation/topology-renderer/views/node-searcher/NodeSearcher.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/208)

Reset cached matched node list

---

src/app/shared/paginator/Paginator.common.scss
src/app/shared/paginator/Paginator.dark.scss
src/app/shared/paginator/Paginator.light.scss
src/app/shared/paginator/Paginator.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/209)

Make the current page indicator in paginator editable

---

src/app/shared/form/radio/RadioButton.light.scss
src/global-styles.light.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/210)

Fix color mismatches for light theme

---

src/app/simulation/simulation-configuration/SimulationConfigurationEditor.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/211)

Adjust epoch timestamps to have second precision

---

src/app/App.tsx
src/app/navigation/Navigation.tsx
src/app/navigation/drawer/DrawerItemGroup.dark.scss
src/app/shared/simulation/Simulation.ts
src/app/shared/simulation/SimulationQueue.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/212)

Default active simulation

---

src/app/simulation/simulation-configuration/SimulationConfigurationEditor.tsx
src/app/simulation/simulation-control/models/SimulationStartedEventResponse.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/213)

Fix attribute casing

---

src/app/data-browser/powergrid-models/PowergridModels.tsx
src/app/settings/Settings.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/214)

Use new life cyle method and remove unused code

---

src/app/shared/form/slide-toggle/SlideToggle.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/215)

Expand the clickable region of the slide toggle

---

src/app/navigation/drawer/DrawerItemGroup.dark.scss
src/app/shared/form/input/Input.dark.scss
src/app/shared/form/textarea/TextArea.dark.scss
src/app/shared/form/textarea/TextArea.light.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/220)

Update border colors for Input and TextArea components for dark theme

---

src/app/shared/form/textarea/TextArea.common.scss
src/app/shared/form/textarea/TextArea.dark.scss
src/app/shared/form/textarea/TextArea.light.scss
src/app/shared/form/textarea/TextArea.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/221)

Redesign focus indicator for TextArea components

---

src/app/shared/misc.ts
src/app/shared/simulation/Simulation.ts
src/app/shared/tabs/ActiveTabIndicator.common.scss
src/app/shared/tabs/ActiveTabIndicator.dark.scss
src/app/shared/tabs/TabGroup.dark.scss
src/app/shared/test-manager/CommOutageEventTable.tsx
src/app/simulation/simulation-configuration/views/test-configuration/TestConfiguration.tsx
src/app/simulation/simulation-configuration/views/test-configuration/comm-outage/CommOutageEventForm.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/222)

Add a function to generate unique IDs

---

src/app/shared/DateTimeService.ts
src/app/shared/form/form-control/FormControl.common.scss
src/app/shared/form/input/Input.common.scss
src/app/shared/form/validation/validation-error-messages/ValidationErrorMessages.common.scss
src/app/shared/test-manager/CommOutageEvent.ts
src/app/shared/test-manager/CommOutageEventTable.tsx
src/app/shared/test-manager/FaultEvent.ts
src/app/shared/test-manager/FaultEventTable.tsx
src/app/simulation/simulation-configuration/SimulationConfigurationEditor.tsx
src/app/simulation/simulation-configuration/views/test-configuration/TestConfiguration.tsx
src/app/simulation/simulation-configuration/views/test-configuration/comm-outage/CommOutageEventForm.tsx
src/app/simulation/simulation-configuration/views/test-configuration/fault/FaultEventForm.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/223)

Convert times in test manager to second precision epoch

---

src/app/shared/simulation/SimulationOutputService.ts
src/app/simulation/measurement-chart/MeasurementChartContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/224)

Use timestamps in simulation outputs for the plots' x axis

---

src/app/App.tsx
src/app/shared/ripple/Ripple.dark.scss
src/app/shared/ripple/Ripple.light.scss
src/app/shared/simulation/SimulationOutputService.ts
src/app/shared/topology/model-dictionary/ModelDictionaryComponent.ts
src/app/simulation/simulation-control/views/plot-model-creator/PlotModelCreator.tsx
src/app/simulation/simulation-labels/SimulationLabel.common.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/226)

Render the plots with correct measurement types

---

src/app/simulation/topology-renderer/TopologyRenderer.common.scss
src/app/simulation/topology-renderer/TopologyRenderer.tsx
src/app/simulation/topology-renderer/TopologyRendererContainer.tsx
src/app/simulation/topology-renderer/models/RenderableTopology.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/227)

Invert 9500 model before rendering

---

src/app/App.tsx
src/app/authentication/AuthenticationContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/231)

Unsusbscribe from the session subject when the component is mounted

---

src/app/simulation/topology-renderer/TopologyRendererContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/233)

Make lat/long detection more dynamic

---

src/app/App.tsx
src/app/shared/simulation/SimulationOutputService.ts
src/app/shared/topology/model-dictionary/ModelDictionaryComponent.ts
src/app/simulation/measurement-chart/MeasurementChart.tsx
src/app/simulation/measurement-chart/MeasurementChartContainer.tsx
src/app/simulation/measurement-chart/models/TimeSeriesDataPoint.ts
src/app/simulation/simulation-control/views/plot-model-creator/PlotModelCreator.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/235)

Fix problem deriving the output measurements for different phases

---

.vscode/settings.json
package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/237)

Upgrade typescript and d3

---

src/app/shared/simulation/SimulationControlService.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/238)

When resuming a paused simulation, set the simulation status to STARTED

---

src/app/simulation/measurement-chart/MeasurementChartContainer.tsx
src/app/simulation/simulation-labels/SimulationLabelsContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/240)

Reset measurement plots and labels when a new simulation starts

---

src/app/simulation/topology-renderer/views/node-searcher/NodeSearcher.common.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/242)

Reduce animation duration in node searcher UI

---

src/app/shared/form/checkbox/CheckBox.common.scss
src/app/shared/form/checkbox/CheckBox.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/243)

Show ripple when clicking on checkbox

---

src/app/navigation/Navigation.tsx
src/app/simulation/measurement-chart/MeasurementChart.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/248)

Set the default y axis's domain to [Infinity, -Inifinity]

---

src/app/shared/form/checkbox/CheckBox.common.scss
src/app/shared/form/radio/RadioButton.common.scss
src/app/shared/form/radio/RadioButton.tsx
src/app/simulation/simulation-control/views/plot-model-creator/PlotModelCreator.common.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/249)

Show ripple when clicking on radio buttons

---

src/app/shared/form/textarea/TextArea.common.scss
src/app/shared/form/textarea/TextArea.dark.scss
src/app/shared/form/textarea/TextArea.light.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/253)

Reduce TextArea component focus indicator's animation duration

---

src/app/simulation/alarms/Alarms.tsx
src/app/simulation/alarms/AlarmsContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/254)

Reset the list of alarms to empty when a new simulation was started

---

src/app/AppContainer.tsx
src/app/models/default-application-state.ts
src/app/shared/state-store/ApplicationState.ts
src/app/simulation/simulation-configuration/SimulationConfigurationEditor.tsx
src/app/simulation/simulation-control/SimulationControlContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/256)

Empty out plot models when a new line name is selected

---

src/app/simulation/measurement-chart/MeasurementChartContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/257)

Download all measurements when simulation is stopped

---

src/app/AppContainer.tsx
src/app/shared/misc.ts
src/app/simulation/simulation-status-logger/SimulationStatusLogger.tsx
src/app/simulation/simulation-status-logger/SimulationStatusLoggerContainer.tsx
src/app/simulation/simulation-status-logger/models/LogMessage.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/258)

Generate a unique ID for each simulation status log message

---

src/app/AppContainer.tsx
src/app/data-browser/logs/LogsContainer.tsx
src/app/data-browser/logs/QueryLogsResultTable.tsx
src/app/data-browser/powergrid-models/PowergridModelsContainer.tsx
src/app/models/message-requests/GetAllFeederModelsRequest.ts
src/app/models/message-requests/GetModelDictionaryRequest.ts
src/app/shared/dialog/DialogContent.tsx
src/app/shared/form/input/Input.tsx
src/app/shared/form/select/OptionListFilter.tsx
src/app/shared/form/select/Select.tsx
src/app/shared/form/textarea/TextArea.tsx
src/app/shared/pop-up/PopUp.tsx
src/app/shared/simulation/SimulationOutputService.ts
src/app/simulation/simulation-configuration/views/service-configuration-tab/ServiceConfigurationTab.tsx
src/app/simulation/topology-renderer/TopologyRenderer.tsx
src/app/simulation/topology-renderer/TopologyRendererContainer.tsx
src/app/simulation/topology-renderer/views/capacitor-menu/CapacitorMenu.tsx
src/app/simulation/topology-renderer/views/regulator-menu/RegulatorMenu.tsx
src/app/simulation/topology-renderer/views/switch-menu/SwitchMenu.tsx
src/app/stomp-client/StompClientContainer.tsx
src/app/websocket-status-watcher/WebsocketStatusWatcher.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/260)

Use optional chaining operator

---

src/app/simulation/simulation-control/views/plot-model-creator/PlotModelCreator.tsx
src/app/simulation/topology-renderer/TopologyRendererContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/261)

Show magnitude and angle in plot names

---

src/app/simulation/simulation-configuration/views/test-configuration-tab/comm-outage/CommOutageEventForm.common.scss
src/app/simulation/simulation-configuration/views/test-configuration-tab/comm-outage/CommOutageEventForm.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/262)

Allow the output list in test configuration to be empty

---

src/app/shared/form/select/Select.common.scss
src/app/shared/form/select/Select.dark.scss
src/app/shared/form/select/Select.tsx
src/app/simulation/topology-renderer/views/capacitor-menu/CapacitorMenu.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/265)

Animate the arrow down icon when opening select components

---

.travis/main.sh
Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/270)

Node version update and travis docker-compose update

---

backend/src/index.ts
backend/src/simulation-coordination/SimulationChannel.ts
backend/src/simulation-coordination/SimulationCoordinator.ts
backend/src/simulation-coordination/SimulationParticipant.ts
frontend/src/app/shared/simulation/SimulationControlService.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/271)

Create a simulation channel for each simulation initiator

---

frontend/src/app/shared/authenticator/services/AuthenticatorService.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/281)

Fix #1195, reload the page on logout to clear the in memory cache

---

frontend/src/app/simulation/measurement-chart/MeasurementChart.common.scss
frontend/src/app/simulation/measurement-chart/MeasurementChart.tsx
frontend/tsconfig.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/284)

If tick values are integers, then display them with no floating point

---

frontend/src/app/simulation/measurement-chart/MeasurementChart.common.scss
frontend/src/app/simulation/measurement-chart/MeasurementChart.dark.scss
frontend/src/app/simulation/measurement-chart/MeasurementChart.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/285)

Label the plot lines that overlap one another

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/App.common.scss
frontend/src/app/shared/form/textarea/TextArea.common.scss
frontend/src/app/shared/form/textarea/TextArea.dark.scss
frontend/src/app/shared/form/textarea/TextArea.light.scss
frontend/src/app/shared/form/textarea/TextArea.tsx
frontend/src/app/simulation/simulation-configuration/views/service-configuration-tab/ServiceConfiguration.tsx
frontend/src/app/stomp-client/StompClient.tsx

- Disable/enable submit button of StompClient based on its form's validity status
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/289)

- Use CodeMirror as the underlying editor for TextArea's

---

frontend/src/app/shared/form/textarea/TextArea.common.scss
frontend/src/app/shared/form/textarea/TextArea.dark.scss
frontend/src/app/shared/form/textarea/TextArea.light.scss
frontend/src/app/shared/form/textarea/TextArea.tsx
frontend/src/app/shared/form/validation/Validators.ts
frontend/src/app/simulation/simulation-configuration/views/application-configuration-tab/ApplicationConfigurationTab.tsx
frontend/src/app/simulation/simulation-configuration/views/service-configuration-tab/ServiceConfiguration.tsx
frontend/src/app/simulation/simulation-configuration/views/simulation-configuration-tab/SimulationConfigurationTab.tsx
frontend/src/app/stomp-client/StompClient.tsx

- Render a squiggly line when a line of text in TextArea fails JSON validation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/291)

- Add a new validator to check for range membership

---

backend/src/simulation-coordination/SimulationChannel.ts
frontend/src/app/AppContainer.tsx
frontend/src/app/navigation/NavigationContainer.tsx
frontend/src/app/shared/plot-model/PlotModel.ts
frontend/src/app/shared/simulation/SimulationOutputMeasurement.ts
frontend/src/app/shared/tooltip/Tooltip.tsx
frontend/src/app/shared/topology/Node.ts
frontend/src/app/shared/topology/SolarPanel.ts
frontend/src/app/shared/topology/model-dictionary/MeasurementType.ts
frontend/src/app/shared/topology/model-dictionary/ModelDictionaryComponent.ts
frontend/src/app/shared/topology/model-dictionary/ModelDictionaryMeasurement.ts
frontend/src/app/shared/topology/model-dictionary/index.ts
frontend/src/app/simulation/measurement-chart/MeasurementChartContainer.tsx
frontend/src/app/simulation/measurement-value-table/MeasurementValueTableContainer.tsx
frontend/src/app/simulation/simulation-control/views/plot-model-creator/PlotModelCreator.tsx
frontend/src/app/simulation/topology-renderer/TopologyRenderer.common.scss
frontend/src/app/simulation/topology-renderer/TopologyRenderer.dark.scss
frontend/src/app/simulation/topology-renderer/TopologyRenderer.light.scss
frontend/src/app/simulation/topology-renderer/TopologyRenderer.tsx
frontend/src/app/simulation/topology-renderer/TopologyRendererContainer.tsx

@bibiraju This PR depends on the other PR I added you to which is https://github.com/GRIDAPPSD/gridappsd-viz/pull/303, so you should test/merge the other one first
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/304)

Render battery shapes

---

backend/src/simulation-coordination/SimulationChannel.ts
frontend/src/app/AppContainer.tsx
frontend/src/app/navigation/NavigationContainer.tsx
frontend/src/app/shared/plot-model/PlotModel.ts
frontend/src/app/shared/simulation/SimulationOutputMeasurement.ts
frontend/src/app/shared/tooltip/Tooltip.tsx
frontend/src/app/shared/topology/Node.ts
frontend/src/app/shared/topology/SolarPanel.ts
frontend/src/app/shared/topology/model-dictionary/MeasurementType.ts
frontend/src/app/shared/topology/model-dictionary/ModelDictionaryComponent.ts
frontend/src/app/shared/topology/model-dictionary/ModelDictionaryMeasurement.ts
frontend/src/app/shared/topology/model-dictionary/index.ts
frontend/src/app/simulation/measurement-chart/MeasurementChartContainer.tsx
frontend/src/app/simulation/measurement-value-table/MeasurementValueTableContainer.tsx
frontend/src/app/simulation/simulation-control/views/plot-model-creator/PlotModelCreator.tsx
frontend/src/app/simulation/topology-renderer/TopologyRenderer.common.scss
frontend/src/app/simulation/topology-renderer/TopologyRenderer.dark.scss
frontend/src/app/simulation/topology-renderer/TopologyRenderer.light.scss
frontend/src/app/simulation/topology-renderer/TopologyRenderer.tsx
frontend/src/app/simulation/topology-renderer/TopologyRendererContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/303)

Render shapes for solar panel nodes

---

frontend/src/app/simulation/simulation-configuration/views/service-configuration-tab/ServiceConfiguration.tsx
frontend/src/app/simulation/simulation-configuration/views/service-configuration-tab/ServiceConfigurationTab.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/305)

Nhuyvan state estimator

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/shared/StompClientService.ts
frontend/src/app/simulation/alarms/views/new-alarm-notification/NewAlarmNotification.common.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/309)

Use StompJS version 5

---

frontend/src/app/shared/ConfigurationManager.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/310)

Use fetch API to retrieve config data

---

frontend/src/app/shared/DateTimeService.ts
frontend/src/app/shared/authenticator/Authenticator.tsx
frontend/src/app/shared/form/validation/Validators.ts
frontend/src/app/shared/overlay/dialog/Dialog.tsx
frontend/src/app/shared/overlay/portal-renderer/PortalRenderer.tsx
frontend/src/app/simulation/alarms/AlarmsContainer.tsx
frontend/src/app/simulation/alarms/views/new-alarm-notification/NewAlarmNotification.tsx
frontend/src/app/simulation/topology-renderer/TopologyRenderer.tsx
frontend/src/app/simulation/topology-renderer/TopologyRendererContainer.tsx
frontend/src/app/simulation/topology-renderer/views/node-searcher/NodeSearcher.common.scss
frontend/src/app/simulation/topology-renderer/views/node-searcher/NodeSearcher.tsx
frontend/src/app/simulation/topology-renderer/views/regulator-control-menu/RegulatorControlMenu.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/315)

Small refactors

---

frontend/src/app/simulation/topology-renderer/TopologyRenderer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/317)

Ignore switches when selecting components with no power to color red

---

frontend/src/app/data-browser/DataBrowser.common.scss
frontend/src/app/data-browser/DataBrowser.dark.scss
frontend/src/app/data-browser/DataBrowser.light.scss
frontend/src/app/data-browser/DataBrowser.tsx
frontend/src/app/data-browser/RequestEditor.tsx
frontend/src/app/data-browser/Response.tsx
frontend/src/app/data-browser/logs/Logs.common.scss
frontend/src/app/data-browser/logs/LogsContainer.tsx
frontend/src/app/data-browser/logs/QueryLogsForm.tsx
frontend/src/app/data-browser/powergrid-models/PowergridModels.tsx
frontend/src/app/data-browser/simulations/Simulations.tsx
frontend/src/app/shared/overlay/notification/Notification.common.scss
frontend/src/app/simulation/simulation-control/views/plot-model-creator/PlotModelCreator.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/321)

Reduce unnecessary updates in PlotModelCreator component

---

frontend/src/app/shared/form/select/Select.tsx
frontend/src/app/shared/paginator/PageChangeEvent.ts
frontend/src/app/shared/paginator/Paginator.tsx
frontend/src/app/shared/paginator/index.ts
frontend/src/app/simulation/topology-renderer/views/node-searcher/NodeSearcher.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/327)

Update the API of Paginator component

---

README.md
frontend/package-lock.json
frontend/package.json
frontend/src/app/settings/Settings.tsx
frontend/src/app/shared/StompClientService.ts
frontend/src/app/simulation/simulation-status-logger/SimulationStatusLogger.tsx
frontend/src/main.development.tsx
frontend/src/main.production.tsx
frontend/src/webpack-injections.d.ts
frontend/webpack.base.config.js
frontend/webpack.development.config.js
frontend/webpack.production.config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/335)

Add an option to conditionally enable CSS hot reload during development

---

frontend/package-lock.json
frontend/package.json
frontend/webpack.base.config.js
frontend/webpack.development.config.js
frontend/webpack.plugins.js
frontend/webpack.production.config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/336)

Enable hot reloading react components during development

---

frontend/src/app/shared/form/form-group/FormGroup.common.scss
frontend/src/app/shared/form/form-group/FormGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/337)

Animate form group's collapsing and expanding

---

frontend/src/app/App.tsx
frontend/src/app/settings/Settings.common.scss
frontend/src/app/settings/Settings.tsx
frontend/src/app/shared/StompClientService.ts
frontend/src/app/shared/form/input/Input.tsx
frontend/src/app/shared/form/select/OptionListFilter.common.scss
frontend/src/app/shared/form/slide-toggle/SlideToggle.tsx
frontend/src/app/shared/overlay/dialog/ConfirmationDialog.common.scss
frontend/src/app/shared/overlay/dialog/ConfirmationDialog.dark.scss
frontend/src/app/shared/overlay/dialog/ConfirmationDialog.light.scss
frontend/src/app/shared/overlay/dialog/ConfirmationDialog.tsx
frontend/src/app/shared/overlay/dialog/DialogContent.tsx
frontend/src/app/shared/overlay/dialog/index.ts
frontend/src/app/shared/simulation/SimulationManagementService.ts
frontend/src/app/simulation/alarms/AlarmsContainer.tsx
frontend/src/app/simulation/simulation-control/SimulationControlContainer.tsx
frontend/src/app/simulation/simulation-status-logger/SimulationStatusLoggerContainer.tsx
frontend/src/app/simulation/topology-renderer/TopologyRenderer.tsx
frontend/src/app/simulation/topology-renderer/TopologyRendererContainer.tsx
frontend/src/app/stomp-client/StompClientContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/339)

Add a new setting to settings UI that allows toggling logging

---

backend/package-lock.json
backend/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/344)

Upgrade dependency to fix security alert reported by GitHub

---

frontend/src/app/settings/Settings.tsx
frontend/src/app/shared/StompClientService.ts
frontend/src/webpack-injections.d.ts
frontend/webpack.base.config.js
frontend/webpack.development.config.js
frontend/webpack.plugins.js
frontend/webpack.production.config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/345)

Remove a flag from webpack build

---

frontend/src/app/stomp-client/StompClient.common.scss
frontend/src/app/stomp-client/StompClient.tsx
frontend/src/app/stomp-client/StompClientContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/347)

Add an input box to change the response topic for stomp client UI

---

frontend/src/app/simulation/expected-result-comparison/models/SimulationVsTimeSeriesRequest.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/349)

[Bug fix] Add missing destination topic

---

frontend/src/app/shared/simulation/SimulationManagementService.ts
frontend/src/app/shared/simulation/SimulationStatusLogMessage.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/354)

[Bug fix] Change how simulation statuses STARTED and PAUSED are detected

---

frontend/src/app/simulation/expected-result-comparison/ExpectedResultComparisonContainer.tsx
frontend/src/app/simulation/expected-result-comparison/models/SimulationVsExpectedRequest.ts
frontend/src/app/simulation/expected-result-comparison/models/SimulationVsTimeSeriesRequest.ts
frontend/src/app/simulation/expected-result-comparison/views/simulation-vs-expected/SimulationVsExpected.tsx
frontend/src/app/simulation/expected-result-comparison/views/simulation-vs-time-series/SimulationVsTimeSeries.common.scss
frontend/src/app/simulation/expected-result-comparison/views/simulation-vs-time-series/SimulationVsTimeSeries.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/355)

Add a button to upload simulation configuration object

---

frontend/package-lock.json
frontend/src/app/App.tsx
frontend/src/app/models/default-application-state.ts
frontend/src/app/navigation/views/drawer/Drawer.tsx
frontend/src/app/shared/buttons/icon-button/IconButton.tsx
frontend/src/app/shared/measurement-limits.ts
frontend/src/app/shared/misc.ts
frontend/src/app/shared/overlay/backdrop/Backdrop.tsx
frontend/src/app/shared/simulation/SimulationOutputMeasurement.ts
frontend/src/app/shared/state-store/ApplicationState.ts
frontend/src/app/simulation/expected-result-comparison/models/ExpectedVsTimeSeriesRequest.ts
frontend/src/app/simulation/expected-result-comparison/models/SimulationVsExpectedRequest.ts
frontend/src/app/simulation/measurement-chart/MeasurementChartContainer.tsx
frontend/src/app/simulation/measurement-chart/models/FetchLimitsFileRequest.ts
frontend/src/app/simulation/simulation-control/SimulationControlContainer.tsx
frontend/src/app/simulation/simulation-control/views/plot-model-creator/PlotModelCreator.tsx
frontend/src/app/simulation/topology-renderer/TopologyRenderer.common.scss
frontend/src/app/simulation/topology-renderer/TopologyRenderer.dark.scss
frontend/src/app/simulation/topology-renderer/TopologyRenderer.light.scss
frontend/src/app/simulation/topology-renderer/TopologyRenderer.tsx
frontend/src/app/simulation/topology-renderer/TopologyRendererContainer.tsx
frontend/src/app/simulation/voltage-violation/VoltageViolation.common.scss
frontend/tsconfig.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/358)

Power flow direction indicators

---

frontend/src/app/simulation/measurement-value-table/MeasurementValueTable.tsx
frontend/src/app/simulation/simulation-status-logger/SimulationStatusLogger.tsx

- Fix typos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/360)

- Hide the simulation log paginator when there are 0 log messages

---

backend/src/simulation-coordination/SimulationCoordinator.ts
backend/src/simulation-coordination/SimulationParticipant.ts
frontend/src/app/simulation/measurement-chart/MeasurementChart.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/361)

Animate measurement chart lines

---

frontend/src/app/shared/overlay/notification/Notification.common.scss
frontend/src/app/shared/overlay/notification/Notification.dark.scss
frontend/src/app/shared/overlay/notification/Notification.light.scss
frontend/src/app/shared/overlay/notification/Notification.tsx
frontend/src/constants.common.scss
frontend/webpack.base.config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/363)

Change how notifications look

---

frontend/src/app/settings/Settings.tsx
frontend/src/app/shared/form/slide-toggle/SlideToggle.light.scss
frontend/src/app/shared/form/textarea/TextArea.dark.scss
frontend/src/app/shared/form/textarea/TextArea.light.scss
frontend/src/app/simulation/measurement-chart/MeasurementChart.common.scss
frontend/src/app/simulation/measurement-chart/MeasurementChart.dark.scss
frontend/src/app/simulation/measurement-chart/MeasurementChart.light.scss
frontend/src/app/simulation/measurement-chart/MeasurementChart.tsx
frontend/src/app/simulation/measurement-chart/MeasurementChartContainer.tsx
frontend/src/app/simulation/simulation-status-logger/SimulationStatusLogger.dark.scss
frontend/src/app/simulation/simulation-status-logger/SimulationStatusLogger.light.scss
frontend/src/app/simulation/simulation-status-logger/SimulationStatusLoggerMessage.dark.scss
frontend/src/app/simulation/simulation-status-logger/SimulationStatusLoggerMessage.light.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/367)

Add buttons to zoom in and out on plots

---

frontend/src/app/simulation/measurement-chart/MeasurementChartContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/369)

[GRIDAPPSD-gridappsd-forum-82] Fix wrong method being called

---

frontend/src/app/settings/Settings.tsx
frontend/src/app/shared/buttons/icon-button/IconButton.light.scss
frontend/src/app/shared/form/form-group/FormGroup.common.scss
frontend/src/app/shared/form/form-group/FormGroup.light.scss
frontend/src/app/shared/form/form-group/FormGroup.tsx
frontend/src/app/shared/form/select/Select.common.scss
frontend/src/app/shared/form/select/Select.tsx
frontend/src/app/shared/form/slide-toggle/SlideToggle.light.scss
frontend/src/app/shared/form/textarea/TextArea.dark.scss
frontend/src/app/shared/form/textarea/TextArea.light.scss
frontend/src/app/shared/overlay/notification/Notification.common.scss
frontend/src/app/shared/overlay/notification/Notification.dark.scss
frontend/src/app/shared/overlay/notification/Notification.light.scss
frontend/src/app/shared/overlay/notification/Notification.tsx
frontend/src/app/simulation/measurement-chart/MeasurementChart.common.scss
frontend/src/app/simulation/measurement-chart/MeasurementChart.dark.scss
frontend/src/app/simulation/measurement-chart/MeasurementChart.light.scss
frontend/src/app/simulation/measurement-chart/MeasurementChart.tsx
frontend/src/app/simulation/measurement-chart/MeasurementChartContainer.tsx
frontend/src/app/simulation/simulation-configuration/views/service-configuration-tab/ServiceConfiguration.common.scss
frontend/src/app/simulation/simulation-configuration/views/service-configuration-tab/ServiceConfiguration.dark.scss
frontend/src/app/simulation/simulation-configuration/views/service-configuration-tab/ServiceConfiguration.tsx
frontend/src/app/simulation/simulation-status-logger/SimulationStatusLogger.dark.scss
frontend/src/app/simulation/simulation-status-logger/SimulationStatusLogger.light.scss
frontend/src/app/simulation/simulation-status-logger/SimulationStatusLoggerMessage.dark.scss
frontend/src/app/simulation/simulation-status-logger/SimulationStatusLoggerMessage.light.scss
frontend/src/app/simulation/topology-renderer/TopologyRenderer.common.scss
frontend/src/app/simulation/topology-renderer/TopologyRenderer.tsx
frontend/src/constants.common.scss
frontend/webpack.base.config.js

Release of version 2020.11.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/370)

Release of version 2020.11.0

---

frontend/src/app/simulation/measurement-chart/MeasurementChart.common.scss
frontend/src/app/simulation/measurement-chart/MeasurementChart.tsx
frontend/src/app/simulation/topology-renderer/TopologyRenderer.tsx

This PR is a fix for this
After the fix
Before the fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/373)

[Bug fix] Fix partial powerflow highlighting of lines

---

frontend/src/app/simulation/topology-renderer/models/OpenOrCloseCapacitorRequest.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/374)

correcting the value of capacitor for open and close

---

frontend/.gitignore
frontend/src/app/shared/topology/Capacitor.ts
frontend/src/app/shared/topology/Regulator.ts
frontend/src/app/shared/topology/SwingNode.ts
frontend/src/app/shared/topology/Transformer.ts
frontend/src/app/simulation/topology-renderer/TopologyRenderer.common.scss

Please see this picture for reference
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/375)

Switch the arrow directions of selected lines and switches

---

frontend/src/app/simulation/simulation-configuration/SimulationConfigurationEditor.tsx
frontend/src/app/simulation/simulation-configuration/views/simulation-configuration-tab/SimulationConfigurationTab.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/387)

Add OpenDSS as another simulator option to simulation configuration

---

.gitignore
frontend/src/app/models/default-application-state.ts
frontend/src/app/settings/Settings.common.scss
frontend/src/app/settings/Settings.tsx
frontend/src/app/shared/DateTimeService.ts
frontend/src/app/shared/form/form-control/FormControl.tsx
frontend/src/app/shared/form/textarea/TextArea.dark.scss
frontend/src/app/shared/form/textarea/TextArea.light.scss
frontend/src/app/shared/overlay/dialog/Dialog.tsx
frontend/src/app/shared/state-store/ApplicationState.ts
frontend/src/app/simulation/alarms/AlarmsContainer.tsx
frontend/src/app/simulation/event-summary/EventSummary.tsx
frontend/src/app/simulation/measurement-chart/MeasurementChart.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/379)

[GRIDAPPSD/GOSS-GridAPPS-D#1426] Add time zone support

---

.travis/build-docker.sh
README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/390)

Update travis login.  Add links to platform documentation

---

.github/workflows/main.yml
.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/407)

Add github actions, disable travis

---

client/src/app/expected-result-comparison/ExpectedResultComparisonContainer.tsx
client/src/app/expected-result-comparison/views/time-series-vs-time-series/TimeSeriesVsTimeSeriesChartResult.tsx
client/src/app/simulation/topology-renderer/TopologyRendererContainer.tsx
client/src/app/simulation/topology-renderer/models/CapacitorVarUpdateRequest.ts
client/src/app/simulation/topology-renderer/models/CapacitorVoltUpdateRequest.ts
client/src/app/simulation/topology-renderer/models/ToggleCapacitorManualModeRequest.ts
client/src/app/simulation/topology-renderer/models/ToggleRegulatorManualModeRequest.ts

Fixes the capacitor and regulator control messages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/429)

Capacitor config

---

client/src/app/common/simulation/SimulationManagementService.ts
client/src/app/simulation/measurement-chart/MeasurementChartContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/436)

fix load demand plot by removing duplicate measurement from MeasurementMap

---

client/src/app/common/simulation/SimulationManagementService.ts
client/src/app/simulation/measurement-chart/MeasurementChartContainer.tsx

Changed Y-axis label to degrees for Angle plots
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gridappsd/gridappsd-viz/437)

Fix display unit for angle plots
